// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJrWMhITIvQrq9DtW_n9Vi804qtRx39wU',
    appId: '1:4039321652:web:814352da87059bb3a28261',
    messagingSenderId: '4039321652',
    projectId: 'tdf-job-bank-c3729',
    authDomain: 'tdf-job-bank-c3729.firebaseapp.com',
    storageBucket: 'tdf-job-bank-c3729.firebasestorage.app',
    measurementId: 'G-EFD0MER4EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6zb9VTkufPgqy1V9cvjAraVXjKyLbSmo',
    appId: '1:4039321652:android:b922ca01f7da42a9a28261',
    messagingSenderId: '4039321652',
    projectId: 'tdf-job-bank-c3729',
    storageBucket: 'tdf-job-bank-c3729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCypDaED5b_xO4Rnqmco1KXk7H5_Pqeu_0',
    appId: '1:4039321652:ios:ea69b6307066bf02a28261',
    messagingSenderId: '4039321652',
    projectId: 'tdf-job-bank-c3729',
    storageBucket: 'tdf-job-bank-c3729.firebasestorage.app',
    iosBundleId: 'com.example.tdfJobBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCypDaED5b_xO4Rnqmco1KXk7H5_Pqeu_0',
    appId: '1:4039321652:ios:ea69b6307066bf02a28261',
    messagingSenderId: '4039321652',
    projectId: 'tdf-job-bank-c3729',
    storageBucket: 'tdf-job-bank-c3729.firebasestorage.app',
    iosBundleId: 'com.example.tdfJobBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJrWMhITIvQrq9DtW_n9Vi804qtRx39wU',
    appId: '1:4039321652:web:1f09cd82462b5b53a28261',
    messagingSenderId: '4039321652',
    projectId: 'tdf-job-bank-c3729',
    authDomain: 'tdf-job-bank-c3729.firebaseapp.com',
    storageBucket: 'tdf-job-bank-c3729.firebasestorage.app',
    measurementId: 'G-826F2N4MT5',
  );
}
